AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'

Style/SymbolArray:
  Enabled: false

# TODO: Remove below!
Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 14

Metrics/MethodLength:
  Max: 21

Metrics/ClassLength:
  Max: 210

Metrics/ModuleLength:
  Max: 220

Layout/EndOfLine:
  # EnforcedStyle: lf
  Enabled: false
